### PR TITLE
Pr schema 220601

### PR DESCRIPTION
**Pull request by pietrodelugas**
Add new candidate schema for PW and CP to adapt it to changes that will be introduced in qe-7.1.  
Main changes are 

* new set of elements and types for new Hubbard correction I/O 
* introduction of elements and types for ESM-RISM calculation taken from @minoru-otani branch

### CODE REVIEW

**Comment by minoru-otani** [comment]
Thank you for updating the xsd file along with the RISM implementation. Now I am using this xsd file in qeschema. But I got the following error.
I specified 'rmm-davidson' in the input file as shown below:
&electrons
diagonalization = 'rmm-davidson'

I'm not sure how to use the regular expression in the enumeration value. This error might be related to line 656:

-----error message from qeschema
XMLSchemaValidationError: failed validating 'rmm-davidson' with XsdEnumerationFacets(['davidson', 'cg', 'ppcg', 'paro', 'rmm(-davidson){0,1}(-paro){01}']):

Reason: value must be one of ['davidson', 'cg', 'ppcg', 'paro', 'rmm(-davidson){0,1}(-paro){01}']

**Comment by pietrodelugas** [comment]
the regular expression maybe is wrong. Let me check it. I will push the fixes in this pull request,  
we had also  to change the tagnames of  `input/rism` and `input/fcp` elements because Fortran reader was confusing them with the two logical flags in `input/controlo_flags`  that have the same names. 

tomorrow I will try to fix qeschema

**Comment by pietrodelugas** [comment]
@minoru-otani  probably the problem was caused by the missing comma. I have improved the regular expressions adding the possibility of spaces at the beginning and the end of the string.

**Comment by minoru-otani** [comment]
@pietrodelugas I still have the same error with qeschema:
-----error message-----
XMLSchemaValidationError: failed validating 'rmm-davidson' with XsdEnumerationFacets(['davidson', 'cg', 'ppcg', 'paro', '\\s*rmm(-davidson|-paro)\\s*']):

Reason: value must be one of ['davidson', 'cg', 'ppcg', 'paro', '\\s*rmm(-davidson|-paro)\\s*']
----------

If I use just "enumeration value="rmm-davidson"", everything went well.
What I did is the following:
1. generate qes_XXX.f90 files using xsdtools with this xsd file.
2. recompile the code (latest develop branch) with new qes_XXX.f90 files
3. do ESM/RISM_example
4. try to read *.xml using python3.9 by importing the qeschema

If I try to use a simple regular expression like "[rR]mm-davidson" in enumeration value, I received the same error.

Sorry for reiterate update the message. I think we can not use the regular expression in "enumeration". If I change it to "pattern", it works.

**Comment by pietrodelugas** [comment]
@minoru-otani  yes you are right if one uses a pattern, one  must use patterns.  I overlooked that diagoType was using enumeration to restrict the values.  Thanks !!!

**Pull request merged**
